const app=document.querySelector('#app');let ws,me={},state={};const say=(type,data={})=>ws.send(JSON.stringify({type,...data}));
function page(h){app.innerHTML='<div class="shell"><header class="top"><div class="brand">Blackthorn Castle<span>A social mystery</span></div><div class="badge">Multiplayer prototype</div></header>'+h+'</div>'}function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function connect(){if(ws)return;ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host);ws.onmessage=e=>receive(JSON.parse(e.data));ws.onclose=()=>page('<section class="card setup"><h2>The castle connection was lost.</h2><p>Refresh to return to the lobby.</p></section>')}
function lobby(){connect();page('<section class="hero"><div class="phase">A social-deduction party game</div><h1>Murder at<br>Blackthorn Castle</h1><p>Create a room, share the code with friends on your Wi-Fi, and uncover who is plotting behind the tartan curtains.</p></section><section class="card setup"><h2>Enter the castle</h2><p>Choose a name, then create a new room or join one your host has made.</p><div class="names"><input id="name" maxlength="20" placeholder="Your name"><input id="room" maxlength="6" placeholder="Room code (to join)"></div><div class="actions"><button class="button primary" id="create">Create a room</button><button class="button secondary" id="join">Join room</button></div></section>');document.querySelector('#create').onclick=()=>enter(true);document.querySelector('#join').onclick=()=>enter(false)}
function enter(create){let name=document.querySelector('#name').value.trim(),room=document.querySelector('#room').value.trim();if(!name)return alert('Please enter your name.');if(!create&&!room)return alert('Enter the room code your host shared.');say(create?'create':'join',{name,room})}
function receive(m){if(m.type==='error')return alert(m.message);if(m.type==='joined'){me=m.me;state=m.state;return lobbyRoom()}if(m.type==='state'){state=m.state;return render()}if(m.type==='role'){me.role=m.role;return role()}if(m.type==='chat'){state.chat=state.chat||[];state.chat.push(m);return chat(m.scope==='murderers')}if(m.type==='end'){state=m.state;return finish(m.message)}}
function lobbyRoom(){page('<section class="card setup"><div class="phase">Room '+state.code+'</div><h2>Guest list</h2><p>Share this code: <strong>'+state.code+'</strong>. You need at least four guests to begin.</p>'+people()+(me.id===state.host?'<div class="actions"><button class="button primary" id="start">Begin the weekend</button></div>':'<div class="note">The host will start when the guest list is complete.</div>')+'</section>');let b=document.querySelector('#start');if(b)b.onclick=()=>say('start')}
function role(){let copy={murderer:'Meet your fellow Murderers in secret and choose a victim each night. Blend in. Deflect. Be charming.',detective:'You receive a useful clue every round. Watch for contradictions.',seer:'You can investigate one guest per game to learn whether they are a Murderer.',faithful:'Find the Murderers before they outnumber the Faithful.'}[me.role];page('<section class="card role"><div class="phase">Private role reveal</div><div class="seal">'+({murderer:'🗡️',detective:'🔎',seer:'🕯️',faithful:'🛡️'}[me.role])+'</div><h1>You are '+({murderer:'a Murderer',detective:'the Detective',seer:'the Seer',faithful:'Faithful'}[me.role])+'.</h1><p>'+copy+'</p><div class="power">Keep this private. Your role is never shown to other players.</div><button class="button primary" id="ready">I understand</button></section>');document.querySelector('#ready').onclick=()=>say('ready')}
function people(){return '<aside class="people"><h3>Castle guests</h3>'+state.players.map(p=>'<div class="person '+(p.alive?'':'dead')+'"><div class="who"><div class="avatar">'+esc(p.name)[0].toUpperCase()+'</div><div><strong>'+esc(p.name)+'</strong><small>'+(!p.alive?'Now haunting the premises':'Still attending breakfast')+'</small></div></div><div class="status">'+(!p.alive?'Ghost':'Present')+'</div></div>').join('')+'</aside>'}
function frame(x){page('<div class="game-head"><div><div class="phase">Room '+state.code+' · '+state.phase+'</div><h1>Blackthorn Castle</h1></div><div class="stat">'+state.players.filter(p=>p.alive).length+' GUESTS REMAIN<br>ROUND '+state.round+'</div></div><div class="grid"><section class="card stage">'+x+'</section>'+people()+'</div>')}
function render(){if(state.phase==='lobby')return lobbyRoom();if(state.phase==='night')return night();if(state.phase==='breakfast')return breakfast();if(state.phase==='roundtable')return table();if(state.phase==='result')return result()}
function night(){let isM=me.role==='murderer'&&me.alive;frame('<div class="phase">Nightfall</div><h2>The castle sleeps.</h2><p class="lede">'+(isM?'Use the private Murderer chat to agree on a victim.':'The Murderers are plotting. Try not to make ominous noises while you wait.')+'</p>'+(isM?'<div id="chat"></div><div id="targets"></div>':'<div class="clue">You will be summoned when breakfast begins.</div>'));if(isM){chat(true);document.querySelector('#targets').innerHTML='<div class="choices">'+state.players.filter(p=>p.alive&&p.id!==me.id).map(p=>'<button class="choice" data-t="'+p.id+'"><strong>Choose '+esc(p.name)+'</strong><span>Only one Murderer needs to submit.</span></button>').join('')+'</div>';document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>say('murder',{target:b.dataset.t}))}}
function breakfast(){frame('<div class="phase">A grim breakfast</div><h2>'+esc(state.victimName)+' will not be joining us.</h2><p class="lede">The butler found them near the library at dawn and adjusted the marmalade service.</p><div class="clue">Tonight’s clue: “'+esc(state.clue)+'”</div>'+(me.id===state.host?'<button class="button primary" id="table">Open the Round Table</button>':'<div class="note">Waiting for the host.</div>'));let b=document.querySelector('#table');if(b)b.onclick=()=>say('roundtable')}
function table(){frame('<div class="phase">Banishment vote</div><h2>Who shall leave the castle?</h2><p class="lede">Use shared chat to compare alibis, then cast your private vote.</p><div id="chat"></div><div class="choices">'+state.players.filter(p=>p.alive&&p.id!==me.id).map(p=>'<button class="choice" data-v="'+p.id+'"><strong>Vote for '+esc(p.name)+'</strong><span>Your vote stays private until everyone votes.</span></button>').join('')+'</div>');chat(false);document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{say('vote',{target:b.dataset.v});document.querySelectorAll('[data-v]').forEach(x=>x.disabled=true)})}
function chat(priv){let slot=document.querySelector('#chat');if(!slot)return;let ms=(state.chat||[]).filter(m=>priv?m.scope==='murderers':m.scope==='table');slot.innerHTML='<div class="chat"><div class="chat-head">'+(priv?'Private Murderer chat':'Round Table conversation')+'</div><div class="chat-log">'+(ms.length?ms.map(m=>'<div class="chat-message"><strong>'+esc(m.name)+':</strong> '+esc(m.text)+'</div>').join(''):'<div class="chat-message">The room is quiet. Uncomfortably quiet.</div>')+'</div><div class="chat-compose"><input id="message" maxlength="160" placeholder="Say something suspicious…"><button class="send" id="send">Send</button></div></div>';let f=()=>{let v=document.querySelector('#message').value.trim();if(v)say('chat',{scope:priv?'murderers':'table',text:v})};document.querySelector('#send').onclick=f;document.querySelector('#message').onkeydown=e=>{if(e.key==='Enter')f()}}
function result(){frame('<div class="phase">The verdict</div><div class="reveal"><h3>'+esc(state.resultName)+' was '+esc(state.resultRole)+'.</h3><p>'+esc(state.resultText)+'</p></div>'+(me.id===state.host?'<button class="button primary" id="next">Continue</button>':'<div class="note">Waiting for the host.</div>'));let b=document.querySelector('#next');if(b)b.onclick=()=>say('next')}
function finish(x){frame('<div class="phase">Final reckoning</div><div class="reveal"><h3>'+esc(x)+'</h3><p>Someone drops a scone. The peacock remains emotionally unavailable.</p></div><button class="button gold" onclick="location.reload()">Return to lobby</button>')}
lobby();
